### PR TITLE
contact form/message

### PR DESCRIPTION
**Pull request by Adrianaito**
- get id from env variable
- change type imports

### CODE REVIEW

**Comment by Adrianaito** [comment]
There is a new env variable

**Comment by yannklein** [comment]
@Adrianaito there is a strange error message from Vercel:
image

**Comment by yannklein** [comment]
Rpobably related to that? 
https://help.formspree.io/hc/en-us/articles/360015130174-Getting-your-form-s-hashid

**Comment by yannklein** [comment]
Nvm, as discussed, the form spree env var was missing in Vercel.

**Review by yannklein — APPROVED** [review]
Fantastic 🎉

**Pull request merged**
